[konsolebox-scripts]
class = portage.sets.base.DummyPackageSet
packages = app-shells/hist app-text/trim-trailing-spaces dev-vcs/git-amend-date-using-reference dev-vcs/git-checkout-last-version dev-vcs/git-diff-blame dev-vcs/git-move net-dns/dnscrypt-proxy-multi sys-apps/binfind sys-apps/hyphenate sys-apps/killtree sys-apps/libfind sys-apps/manfind sys-apps/rcopy sys-apps/tail-follow-grep sys-apps/xn sys-block/map-partitions sys-boot/build-initramfs
