#!/bin/bash

set -f +o posix && shopt -s extglob || exit

function get_common_prefix {
	local a b i IFS=/
	a=($1) b=($2) i=0

	for (( ; i < ${#a[@]}; ++i )); do
		[[ ${a[i]} == "${b[i]}" ]] || break
	done

	__=${a[*]:0:i}
}

function get_common_prefix_multi {
	__=${1%/*}

	while shift; [[ ${1+.} ]]; do
		get_common_prefix "$__" "${1%/*}"
	done
}

function main {
	local files_to_commit test_dir= ebuilds __

	readarray -t files_to_commit < <(git status --porcelain |
			awk '/^[AMD]/ { print substr($0, 4) }')

	if [[ ${#files_to_commit[@]} -gt 0 ]]; then
		get_common_prefix_multi "${files_to_commit[@]}"

		if [[ -z $__ || $__ == +([!/-])-+([!/-]) || $__ == +([!/-])-+([!/-])/* ]]; then
			if [[ $__ ]]; then
				local IFS=/
				set -- $__
				test_dir="${*:1:2}"
			fi

			readarray -t ebuilds < <(find "${test_dir}" -name '*.ebuild' -exec grep -Ple \
					"KEYWORDS=.*[ \"'=][[:lower:]][[:alnum:]-]+" -- '{}' +)

			if [[ ${#ebuilds[@]} -gt 0 ]]; then
				echo "The following ebuilds have stable keywords: "
				printf '%s\n' "${ebuilds[@]}"
				return 1
			fi

			if [[ ${GIT_PRE_COMMIT_SKIP_REPOMAN-} != @(true|1) ]] && type -P repoman >/dev/null; then
				echo Repoman:
				( [[ -z ${test_dir} ]] || cd -- "${test_dir}" && repoman ) || return 1
				echo
			fi

			if [[ ${GIT_PRE_COMMIT_SKIP_PKGCHECK_SCAN-} != @(true|1) ]] && type -P pkgcheck >/dev/null; then
				local pkgcheck=(pkgcheck scan --exit=error)

				if [[ -e helpers/profiles.mask ]]; then
					readarray -t profiles < helpers/profiles.mask || return 1
					IFS=, eval 'pkgcheck+=("--profiles=${profiles[*]/#/-}")'
				fi

				echo "Pkgcheck scan:"
				( [[ -z ${test_dir} ]] || cd -- "${test_dir}" && "${pkgcheck[@]}" ) || return 1
				echo
			fi
		fi
	fi

	return 0
}

main
